name: "Setup Build Environment"
description: "Install everything needed to build"

runs:
  using: "composite"
  steps:
  - name: Install dependencies
    shell: bash
    run: |
      python -m pip install --upgrade pip
  - name: Install Poetry
    shell: bash
    run: |
      # curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3
      # source $HOME/.poetry/env
      # poetry -n init
      pip install --user poetry
      pip install "mypy==0.910"
