name: PR Python 🐍 to Switch Repo

on:
  pull_request:
    branches:
      - master

jobs:
  code-quality-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.10.0
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.0

    - name: Setup the Python Environment by installing Poetry
      uses: ./.github/actions/setup-python-build-env

    - name: Code Quality Check
      shell: bash
      run: |
        poetry config http-basic.pypi-switch $PYPI_USER $PYPI_PASS
        poetry update
        poetry install
        poetry run pytest tests
        poetry run black --check --diff --line-length=88 slac tests
      env:
        TAG_VERSION: ${{ steps.context.outputs.TAG_VERSION }}
        PYPI_USER: ${{ secrets.PYPI_USER }}
        PYPI_PASS: ${{ secrets.PYPI_PASS }}